# -*- coding: utf-8 -*-
"""cs3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19NA8ZjZdiW5xLPSiy7iGOYNtLJJ2kCMg

Strategia inwestycyjna (decyzje wejścia i wyjścia) dla spółki  Apple (AAPL), test w okresie od 01.01.2024 - 06.05.2024
"""

pip install ta

import pandas as pd
import numpy as np
import yfinance as yf
from ta.momentum import RSIIndicator
from ta.trend import SMAIndicator
from ta.volatility import AverageTrueRange

# Pobranie danych giełdowych AAPL od 2020 roku
ticker = "AAPL"
start = "2020-01-01"
end   = "2024-05-07"

data = yf.download(ticker, start=start, end=end)
data.dropna(inplace=True)

data.columns = data.columns.get_level_values(0)
data.columns = ["Open", "High", "Low", "Close", "Volume"]

#Wskaźniki
# RSI - momentum
rsi_period = 14
data["RSI"] = RSIIndicator(close=data["Close"], window=rsi_period).rsi()

# SMA_20 - śr. krocząca
sma_window = 20
data["SMA_20"] = SMAIndicator(close=data["Close"], window=sma_window).sma_indicator()

# ATR - do SL/TP
atr_period = 14
atr = AverageTrueRange(
    high=data["High"],
    low=data["Low"],
    close=data["Close"],
    window=atr_period
)
data["ATR"] = atr.average_true_range()

# Lag1 Close - opóźnienie cen close
data["Close_lag1"] = data["Close"].shift(1)


data.dropna(inplace=True)
print(data.columns)

data = data.copy()
data.columns = [str(c) for c in data.columns]  # bez multindexu

data

from prophet import Prophet
from sklearn.metrics import mean_absolute_error
from itertools import product

# Przygotowanie danych dla Prophet
df = data.copy()
df_prophet = pd.DataFrame({
    "ds": df.index,
    "y": df["Close"],
    "RSI": df["RSI"],
    "SMA_20": df["SMA_20"],
    "ATR": df["ATR"],
    "Close_lag1": df["Close_lag1"]
})
df_prophet["ds"] = pd.to_datetime(df_prophet["ds"])
print(df_prophet)

# Podział na zbiór test i train
train_df = df_prophet[df_prophet["ds"] < "2024-01-01"]
test_df_prophet = df_prophet[df_prophet["ds"] >= "2024-01-01"]


# Siatka hiperparametrów
cp_scales = [0.01, 0.05, 0.1]
season_scales = [1.0, 5.0, 10.0]

best_params = None
best_mae = np.inf

#Przeszukiwanie siatki hiperparametrów
for cp, ss in product(cp_scales, season_scales):
    m = Prophet(
        changepoint_prior_scale=cp,
        seasonality_prior_scale=ss,
        daily_seasonality=False,
        weekly_seasonality=True,
        yearly_seasonality=False
    )
    # dodatek regresorów
    for reg in ["RSI", "SMA_20", "ATR", "Close_lag1"]:
        m.add_regressor(reg)

#trenowanie na danych hist
    m.fit(train_df)

    future = train_df[["ds", "RSI", "SMA_20", "ATR", "Close_lag1"]].copy()
    forecast = m.predict(future)

#MAE
    mae = mean_absolute_error(train_df["y"], forecast["yhat"])
    if mae < best_mae:
        best_mae = mae
        best_params = {"changepoint_prior_scale": cp, "seasonality_prior_scale": ss}

print("Najlepsze parametry:", best_params, "MAE:", best_mae)

#model z najlepszymi hiperparametrami
m_best = Prophet(
    changepoint_prior_scale=best_params["changepoint_prior_scale"],
    seasonality_prior_scale=best_params["seasonality_prior_scale"],
    daily_seasonality=False,
    weekly_seasonality=True,
    yearly_seasonality=False
)
for reg in ["RSI", "SMA_20", "ATR", "Close_lag1"]:
    m_best.add_regressor(reg)

m_best.fit(train_df)

# Przygotowanie danych testowych
future_test = test_df_prophet[["ds", "RSI", "SMA_20", "ATR", "Close_lag1"]]
forecast_test = m_best.predict(future_test)
df.loc[test_df_prophet["ds"], "yhat"] = forecast_test["yhat"].values

threshold = 0.001

df["yhat_shift1"] = df["yhat"].shift(1)  # prognoza na dzisiejszy dzień wygenerowana wczoraj
df["signal"] = 0

#wejście w longa
long_cond = (
    (df["yhat_shift1"] > df["Close"] * (1 + threshold)) &
    (df["Close"] > df["SMA_20"]) &
    (df["RSI"] < 70)
)

df.loc[long_cond, "signal"] = 1

test_start = "2023-12-31"
test_end   = "2024-05-07"
test_df = df.loc[test_start:test_end].copy()
test_df

pip install backtesting

# TRAIN: 2020–2023
train_data = data.loc['2020-01-01':'2023-12-31'].copy()
train_data['Prediction'] = df.loc['2020-01-01':'2023-12-31', 'yhat']

# TEST: 2024
test_data = data.loc['2024-01-01':'2024-12-31'].copy()
test_data['Prediction'] = df.loc['2024-01-01':'2024-12-31', 'yhat']

from backtesting import Strategy, Backtest
class HighWinRateStrategyy(Strategy):
    tp_atr = 0.6
    sl_atr = 1.2
    threshold = 0.001
    rsi_upper = 60
    rsi_lower = 40
    atr_filter = 0.7

    def init(self):
      self.pred = self.I(lambda: self.data.Prediction)
      self.atr = self.I(lambda: self.data.ATR)
      self.rsi = self.I(lambda: self.data.RSI)
      self.atr_median = np.median(self.data.ATR)

    def next(self):
        price = self.data.Close[-1]
        vol = self.atr[-1]

        #brak handlu przy niskim ATR
        if vol < self.atr_median * self.atr_filter:
            return

        # Rsi ok. 50 - nie handluj
        if 45 < self.rsi[-1] < 55:
            return

        # ignoruj płaskie sygnały
        if abs(self.pred[-1] - price) < price * 0.001:
            return

        sl_dist = vol * self.sl_atr
        tp_dist = vol * self.tp_atr

        signal_long = (
            self.pred[-1] > price * (1 + self.threshold)
            and self.rsi[-1] < self.rsi_upper
        )

        signal_short = (
            self.pred[-1] < price * (1 - self.threshold)
            and self.rsi[-1] > self.rsi_lower
        )

        #wyjście
        if signal_short and self.position.is_long:
            self.position.close()
        if signal_long and self.position.is_short:
            self.position.close()

        # Wejścia
        if signal_long and not self.position:
            self.buy(sl=price - sl_dist, tp=price + tp_dist)
        elif signal_short and not self.position:
            self.sell(sl=price + sl_dist, tp=price - tp_dist)

bt_train = Backtest(train_data, HighWinRateStrategyy, cash=10000, commission=0.001)

stats_train, heatmap_train = bt_train.optimize(
    tp_atr=[0.4, 0.5, 0.6, 0.7, 0.8],
    sl_atr=[1.0, 1.2, 1.4],
    threshold=[0.0010, 0.0015, 0.0020, 0.0025],
    rsi_upper=[45, 50, 55, 60],
    rsi_lower=[30, 35, 40],
    atr_filter=[0.5, 0.6, 0.7, 0.8],

    maximize='Return [%]',
    constraint=lambda p: p.tp_atr <= p.sl_atr * 1.5,
    return_heatmap=True
)

print("\n--- NAJLEPSZE PARAMETRY (TRAIN) ---")
print(stats_train._strategy)

best_params = stats_train._strategy

bt_test = Backtest(test_data, HighWinRateStrategyy, cash=10000, commission=0.001)

strategy_params = {
    'tp_atr': best_params.tp_atr,
    'sl_atr': best_params.sl_atr,
    'threshold': best_params.threshold,
    'rsi_upper': best_params.rsi_upper,
    'rsi_lower': best_params.rsi_lower,
    'atr_filter': best_params.atr_filter
}

stats_test = bt_test.run(**strategy_params)

print("wyniki na test")
print(stats_test)

"""W badanym okresie strategia osiągnęła stopę zwrotu +8.87%, podczas gdy proste kup i trzymaj (Buy & Hold) dla AAPL wygenerowało wynik –2.44%. Oznacza to, że strategia pokonała rynek o ponad 11 punktów procentowych, mimo że okres testowy obejmował fragment rynku o ograniczonym trendzie wzrostowym.

Strategia wykonała 27 transakcji, co odpowiada jej charakterowi swingowemu. Nie jest nadmiernie aktywna, ale reaguje na wyraźne sygnały z modelu predykcyjnego i wskaźników technicznych.

Kluczowym atutem strategii jest wysoki poziom bezpieczeństwa kapitału, potwierdzony niskim maksymalnym obsunięciem (Max Drawdown -3.48%) oraz wysokim wskaźnikiem Profit Factor (2.23).
"""

